# pnpm-workspace.yaml
packages:
  - 'apps/*'
  - 'packages/*'

# 使用 pnpm 10 的新特性：Catalogs
# 这样在子项目中只需写 "react": "catalog:" 即可引用
catalog:
  react: "^19.2.0"
  react-dom: "^19.2.0"
  next: "^16.1.0"
  typescript: "^5.7.0"
  tailwindcss: "^4.0.0"